### PR TITLE
Fixes Bug #35 - Remove unwanted spaces before @, # symbols and in embedded http links…

### PR DESCRIPTION
**Pull request by kanihal**
I'm using lxml to remove unwanted child elements of \<a\> tag in the tweet paragraph. I tried doing it with scrapy 'Selector' but I could not find a way to remove the child sub-elements of an element with 'Selector', hence using lxml.

### CODE REVIEW

**Comment by jonbakerfish** [comment]
Thanks for contributing. I'll leave this open let the users do their homework ;)

**Comment by okomarov** [comment]
@jonbakerfish What's the homework? Do you need a review?

**Comment by jonbakerfish** [comment]
@okomarov The homework which can help them learn about how to handle the data properly :)

**Comment by okomarov** [comment]
Fair enough

> @okomarov The homework which can help them learn about how to handle the data properly :)

**Comment by mrjcleaver** [comment]
Are you saying that not every user of this TweetScraper would want this patch?

**Pull request closed without merging**
