### PR TITLE
solve the warning about `scrapy.conf` is deprecated.

### PR DESCRIPTION
**Pull request by Cen005**
ScrapyDeprecationWarning: Module `scrapy.conf` is deprecated, use `crawler.settings` attribute instead
  from scrapy.conf import settings

### CODE REVIEW

**Comment by jonbakerfish** [comment]
Thanks for contributing. What is the version of scrapy you're using?

**Comment by Cen005** [comment]
scrapy 1.4

**Comment by jeromecc** [comment]
Hi!
Current version of Scrapy for Python2.7 is 1.7.1
The warning became an import error:
```
(tmpts) elkcloner@debian:~/tmp/TweetScraper/TweetScraper$ scrapy list
Traceback (most recent call last):
  File "/home/elkcloner/.virtualenvs/tmpts/bin/scrapy", line 6, in <module>
    from scrapy.cmdline import execute
  File "/home/elkcloner/.virtualenvs/tmpts/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 10, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/home/elkcloner/.virtualenvs/tmpts/local/lib/python2.7/site-packages/scrapy/crawler.py", line 11, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/home/elkcloner/.virtualenvs/tmpts/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 14, in <module>
    from scrapy.core.scraper import Scraper
  File "/home/elkcloner/.virtualenvs/tmpts/local/lib/python2.7/site-packages/scrapy/core/scraper.py", line 18, in <module>
    from scrapy.core.spidermw import SpiderMiddlewareManager
  File "/home/elkcloner/.virtualenvs/tmpts/local/lib/python2.7/site-packages/scrapy/core/spidermw.py", line 13, in <module>
    from scrapy.utils.conf import build_component_list
  File "/home/elkcloner/.virtualenvs/tmpts/local/lib/python2.7/site-packages/scrapy/utils/conf.py", line 4, in <module>
    import configparser
ImportError: No module named configparser
(tmpts) elkcloner@debian:~/tmp/TweetScraper/TweetScraper$ pip show scrapy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.                                                                                                                                    
Name: Scrapy
Version: 1.7.1
Summary: A high-level Web Crawling and Web Scraping framework
Home-page: https://scrapy.org
Author: Scrapy developers
Author-email: None
License: BSD
Location: /home/elkcloner/.virtualenvs/tmpts/lib/python2.7/site-packages
Requires: six, w3lib, queuelib, PyDispatcher, cssselect, parsel, pyOpenSSL, Twisted, service-identity, lxml
Required-by:
```
I could solve the bug by following this https://stackoverflow.com/questions/54717251/scrapydeprecationwarning-module-scrapy-conf-is-deprecated-use-crawler-setti

```
from scrapy.utils.project import get_project_settings
SETTINGS = get_project_settings()
```

Thanks for sharing your scraper with a free software license.

**Comment by jonbakerfish** [comment]
Fixed in https://github.com/jonbakerfish/TweetScraper/pull/58

**Pull request closed without merging**
